### PR TITLE
Fix for #49 (scoped package dependencies)

### PR DESCRIPTION
**Pull request by dsebastien**
I've modified the regex and added a test for validation

### CODE REVIEW

**Comment by TechNickAI** [comment]
Thanks! Have a beer on me with @changetip

**Comment by changetip** [comment]
Hi @dsebastien, @gorillamania sent you a tip worth a beer ($3.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/926009)**.

**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by TechNickAI** [comment]
This is now live with 0.6.1

**Comment by dsebastien** [comment]
Great, thanks! :)

**Pull request merged**
