### PR TITLE
fix: don't require version or name if package has "private": true

### LINKED ISSUE #84: Feature: Don't require version if package has `"private": true`
While it is valid for a private package (`"private": true`) to have a version, it certainly shouldn't _require_ one.

Tools like changeset require that you remove the private package version number (instead of, say providing a useless one like 0.0.1) or it will try to manage that version, even if the package is private. Ideally this package would just allow no versions on private packages.

(Moving the discussion from https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues/250 to here)

### PR DESCRIPTION
**Pull request by hyoban**
fix #84

### CODE REVIEW

**Comment by hyoban** [comment]
@JoshuaKGoldberg Hi, Can you help me take a look at this PR?

**Comment by hyoban** [comment]
Sorry to ping @JoshuaKGoldberg again.

**Comment by JoshuaKGoldberg** [comment]
OH! Oh no! I'm very sorry to leave you hanging on this, I have no idea how I missed multiple notifications!

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM! Clear implementation & tests, nicely done. ⚡

**Comment by JoshuaKGoldberg** [comment]
Published in [`package-json-validator@0.6.5`](https://www.npmjs.com/package/package-json-validator/v/0.6.5). Thanks @hyoban! 🚀

**Pull request merged**
